export { Header } from './Header';
export { Container } from './Container';
export { Footer } from './Footer';
export { SectionTitle } from './SectionTitle';
export { Card } from './Card';
export { Pagination, Navigation } from './Swiper';
export { PopupSlider } from './PopupSlider';
export { Tabs } from './Tabs';
export { Pagination as AppPagination } from './Pagination';
export { DocCard } from './DocCard';
